# Generated by Django 6.0.6 on 2026-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.CharField(default='Core', help_text='Badge label, e.g. Framework, Language', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='color',
            field=models.CharField(default='#7c6fff', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#7c6fff', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'DSA & Tools')], max_length=20),
        ),
    ]
